# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # Les options valides de drivers incluent "gd" ou "gmagick" ou "imagick"
    driver: "gd"

    filter_sets:
        photo_page:
            quality: 75
            filters:
                thumbnail:
                    size: [800, 400]
                    mode: outbound
                background:
                    color: '#000000'
                    size: [804, 404]
                    position: center

        photo_article:
            quality: 75
            filters:
                scale:
                    dim: [300, 200]           
                    
        vignette:
            quality: 75
            filters:
                upscale:
                    min: [150, 100]
                thumbnail:
                    size: [150,100]

        mini:
            quality: 75
            filters:
                upscale:
                    min: [60, 60]
                thumbnail:
                    size: [60,60]  

        logo:
            quality: 75
            filters:
                scale:
                    dim: [60, 40]
